### ISSUE TITLE
ImportError: No module named 'ABE_ExpanderPi'

### ISSUE THREAD

**Issue by ossvirt** [abelectronicsuk/ABElectronics_Python3_Libraries#1]
Hi, I'm having trouble getting my Expander Pi board running. I'm trying to test the ADC but the code cannot find the necessary module.

This is the full error, from Python 3.4.2 Shell on Raspberry Pi Raspbian Jessie -:

    Traceback (most recent call last):
      File "/home/pi/Desktop/adctest.py", line 3, in <module>
        from ABE_ExpanderPi import ADC
    ImportError: No module named 'ABE_ExpanderPi'
    >>> 

I've followed the instructions on [https://github.com/abelectronicsuk/ABElectronics_Python3_Libraries/tree/master/ExpanderPi](https://github.com/abelectronicsuk/ABElectronics_Python3_Libraries/tree/master/ExpanderPi) and [https://www.abelectronics.co.uk/kb/article/1/i2c--smbus-and-raspbian-wheezy](https://www.abelectronics.co.uk/kb/article/1/i2c--smbus-and-raspbian-wheezy)

Running the command:

    export

The output includes the line:

    declare -x PYTHONPATH=":/home/pi/ABElectronics_Python3_Libraries/ExpanderPi/"

So the Python Path should be known.

Thanks for any help, cheers.

**Comment by ossvirt** [comment]
Ah I think I need to enable SPI as well..

[https://www.abelectronics.co.uk/forums/thread/demo-iowrite-py-problem/](https://www.abelectronics.co.uk/forums/thread/demo-iowrite-py-problem/)

[https://www.abelectronics.co.uk/kb/article/2/spi-and-raspbian-linux-on-a-raspberry-pi](https://www.abelectronics.co.uk/kb/article/2/spi-and-raspbian-linux-on-a-raspberry-pi)

**Comment by abelectronicsuk** [comment]
Please can you try running the demo scripts in the same folder as the expander pi libaries and see if you still get the same errors?

**Comment by ossvirt** [comment]
Thanks - that solves the locations for the ABElectronics scripts but it also cannot find the spidev module.

    ImportError: No module named spidev

I followed [this guide](https://www.abelectronics.co.uk/kb/article/2/spi-and-raspbian-linux-on-a-raspberry-pi)

**Comment by abelectronicsuk** [comment]
Please can you try installing spidev using the instructions on https://www.abelectronics.co.uk/kb/article/2/spi-and-raspbian-linux-on-a-raspberry-pi

**Comment by ossvirt** [comment]
That's the guide I used. See above.

**Comment by abelectronicsuk** [comment]
It could possibly be a permissions problem with spidev.  Can you try running the script using sudo and see if that works?

**Comment by ossvirt** [comment]
Success! It wasn't root user I needed though, it was Python 3 instead of Python 2. When I opened the script it chose the Python2 IDLE instead of Python3 IDLE. Silly mistake. Thanks for the help.

**Comment by abelectronicsuk** [comment]
Thank you for the update. I am glad that you found the fix for the issue.
