### ISSUE TITLE
Help python 3 users

### ISSUE THREAD

**Issue by judgewooden** [abelectronicsuk/ABElectronics_Python3_Libraries#2]
The difference in ABE_helpers.py between python3 and python is:

python3: raise ImportError("python-smbus not found'")
python2: raise ImportError("python-smbus not found. Install with 'sudo apt-get install python-smbus'")

suggest adding text: **Install with 'sudo apt-get install python3-smbus'**

**Comment by abelectronicsuk** [comment]
Thank you for noticing the missing text.  I have added it into the header error code in ABE_helpers.py
