### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by tadas-s** [abelectronicsuk/ABElectronics_Python3_Libraries#6]
Hello,

Any plans to publish this as [PyPI][1] package? Or at least package it up for that so it can be installed using `pip` from github directly:

```
$ pip install git+https://github.com/abelectronicsuk/ABElectronics_Python3_Libraries.git
Collecting git+https://github.com/abelectronicsuk/ABElectronics_Python3_Libraries.git
  Cloning https://github.com/abelectronicsuk/ABElectronics_Python3_Libraries.git to /tmp/pip-4x8t8c8f-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/tadas/.virtualenvs/spaceship/lib/python3.4/tokenize.py", line 438, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-4x8t8c8f-build/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-4x8t8c8f-build/
```

Many Thanks,
Tadas

[1]: https://pypi.python.org/pypi

**Comment by tadas-s** [comment]
OK, I gave it a go and for the first step came up with this: #7 

The whole project could be structured better, but it's not a big deal at all, works well anyway.

**Comment by abelectronicsuk** [comment]
Hello Tadas

I will look at making the library available as a PyPI package.  We are currently looking at merging our Python 2 and Python 3 libraries into a single library that is compatible with all versions of Python so if you have any ideas on how we can better structure the library I would appreciate the feedback.
